FROM almalinux:9
ENV course="devops" \
    duration="120HRS" 
ARG trainer="joindevops"
RUN echo "Hi, Course is :${course}, duraiton is ${duration}, trainer is: ${trainer}, version: ${version}"
CMD ["sleep", "1000"]